name: khane_behdasht
description: اپلیکیشن آفلاین خانه بهداشت پزشک خانواده
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shamsi_date: ^1.1.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
